task_tracker/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: 'Account', controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  resources :tasks do
    post :reshuffle, on: :collection
    post :complete, on: :member
  end

  root "tasks#index"
end

task_tracker/app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: %i[doorkeeper]
  validates_uniqueness_of :email, allow_blank: true

  delegate :admin?, to: :role
  has_many :tasks

  scope :employee, -> { where(role: :employee) }

  def role
    super.inquiry
  end

  def human_id
    [name, email].compact.join(' — ')
  end

  def self.from_omniauth(auth)
    where(public_id: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.role = auth.info.role
    end
  end

  def update_doorkeeper_credentials(auth)
    update(
      doorkeeper_access_token: auth.credentials.token,
      doorkeeper_refresh_token: auth.credentials.refresh_token
    )
  end
end

task_tracker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  DEFAULT_EVENT_VERSION = 1

  def current_event_version
    DEFAULT_EVENT_VERSION
  end
end

task_tracker/app/models/event.rb
# frozen_string_literal: true

class Event
  delegate :current_event_version, :event_data, to: :object

  def initialize(object)
    @object = object
  end

  def produce(action:, topic: nil)
    topic ||= build_topic
    payload = EventPayload.new(self, action)
    payload.validate!

    send_event(topic: topic, payload: payload.as_json)
  end

  def owner_name
    object.class.name
  end

  private

  attr_reader :data, :object, :action

  def build_topic
    owner_name.downcase.pluralize
  end

  def send_event(topic:, payload:)
    WaterDrop::SyncProducer.call(payload.to_json, topic: topic)
  end
end

task_tracker/app/models/event_payload.rb
class EventPayload
  delegate :validate!, :valid?, :errors, to: :validator

  def initialize(event, action)
    @event = event
    @action = action
  end

  def as_json
    {
      event_id: generate_event_id,
      event_version: current_event_version,
      event_name: build_event_name,
      event_time: Time.zone.now.to_s,
      producer: 'task_tracker',
      data: event_data
    }
  end

  private

  attr_reader :event, :action
  delegate :owner_name, :event_data, :current_event_version,  to: :event

  def generate_event_id
    SecureRandom.uuid
  end

  def build_event_name
    [event.owner_name, action].join('_').camelize
  end

  def validator
    @validator ||= PayloadValidator.new(
      payload: as_json,
      object_name: owner_name,
      action: action,
      version: current_event_version
    )
  end
end

task_tracker/app/models/payload_validator.rb
class PayloadValidator
  Error = Class.new StandardError

  def self.valid_event?(payload:, name:, action:, version:)
    validator = new(payload: payload, name: name, action: action, version: version)
    validator.valid?
  end

  def initialize(payload:, object_name:, action:, version:)
    @payload = payload
    @object_name = object_name
    @action = action
    @version = version
  end

  def valid?
    validation_result.success?
  end

  def validate!
    raise Error, "Invalid event #{validator.errors}" unless valid?
  end

  def errors
    validation_result.result
  end

  private

  attr_reader :payload, :object_name, :action, :version

  def validation_result
    SchemaRegistry.validate_event(payload, schema_path, version: version)
  end

  def schema_path
    [object_name.downcase, action].join('.')
  end
end

task_tracker/app/models/task.rb
class Task < ApplicationRecord
  STATUSES = %w[in_progress completed].freeze
  CURRENT_EVENT_VERSION = 1

  validates :title, :status, presence: true
  validates :status, inclusion: STATUSES
  scope :in_progress, -> { where(status: :in_progress) }
  scope :completed, -> { where(status: :completed) }

  belongs_to :account
  before_validation :preset_defaults
  after_create :notify_assigned

  delegate :in_progress?, to: :status
  delegate :public_id, to: :account, prefix: true

  def account_assign
    account.human_id
  end

  def status
    super.inquiry
  end

  def belongs_to?(account_to_check)
    account.id == account_to_check.id
  end

  def event_data
    as_json(only: %w[public_id title status], methods: %w[account_public_id])
  end

  def assign!(account)
    update(account: account)
    notify_assigned
  end

  def complete!
    update(status: :completed)
    notify_completed
  end

  def current_event_version
    CURRENT_EVENT_VERSION
  end

  private

  def preset_defaults
    self.status ||= 'in_progress'
    self.public_id ||= SecureRandom.uuid
  end

  def notify_assigned
    Event.new(self).produce(action: :assigned)
  end

  def notify_completed
    Event.new(self).produce(action: :completed)
  end
end

task_tracker/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  before_action :set_task, only: %i[ edit update destroy complete ]

  def index
    render locals: { tasks: tasks }
  end

  def reshuffle
    employees = Account.employee
    Task.in_progress.each { |task| task.assign!(employees.sample) }

    redirect_to tasks_url, notice: "Перемешали задачки"
  end

  def complete
    current_user.tasks.find(task_id).complete!
    redirect_to tasks_url, notice: "Задача закрыта"
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_url, notice: "Задача создана"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @task.update(task_params)
      redirect_to task_url(@task), notice: "Task was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy

    redirect_to tasks_url, notice: "Task was successfully destroyed."
  end

  private

  def tasks
    if current_user.admin?
      Task.all
    else
      current_user.tasks
    end
  end

  def set_task
    @task = Task.find(task_id)
  end

  def task_id
    params[:id]
  end

  def task_params
    params.require(:task).permit(:title, :account_id)
  end
end

task_tracker/app/helpers/tasks_helper.rb
module TasksHelper
end

task_tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

task_tracker/app/views/tasks/_form.html.erb
<%= form_with(model: task) do |f| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :account %>
    <%= f.collection_select :account_id, Account.all, :id, :human_id %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

task_tracker/app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
</div>

task_tracker/app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Отменить и вернуться", tasks_path %>
</div>

task_tracker/app/views/tasks/index.html.erb
<% if tasks.empty? %>
  <h1>Для вас сейчас нет задач</h1>
  <p><%= link_to "Добавить", new_task_path %></p>
<% end %>

<% if tasks.any? %>
  <h1>Задачи</h1>
  <p><%= link_to "Добавить", new_task_path %></p>
  <p><%= link_to "Перемешать", reshuffle_tasks_path, data: { "turbo-method": :post } %></p>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Задача</th>
        <th>Статус</th>
        <th>Попуг</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% tasks.each do |task| %>
        <tr>
          <td><%= task.id %></td>
          <td><%= task.title %></td>
          <td><%= task.status %></td>
          <td><%= task.account_assign %></td>
          <td>
            <% if task.in_progress? && task.belongs_to?(current_user) %>
              <%= link_to 'Сделал', complete_task_url(task), data: { "turbo-method": :post } %>
            <% end %>
          </td>
          <td>
            <% if current_user.admin? %>
              <%= link_to 'Редактировать', edit_task_path(task) %>
              <%= link_to 'Удалить', task, data: { "turbo-method": :delete, confirm: 'Are you sure?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

task_tracker/app/views/tasks/new.html.erb
<h1>Добавление задачи</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Отменить и вернуться", tasks_path %>
</div>

task_tracker/app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>